
### CREATE
POST http://localhost:8000/api/parkingLots HTTP/1.1
content-type: application/json
//x-token: 

[
{
    "userName": "NewProject",
    "calle": "Teatinos",
    "numero":690,
    "comuna": "Santiago",
    "cantidad": 2,
    "lat": "-33.435604661151714",
    "long": "-70.65610078622993"
}
]
###GETALL
GET http://localhost:8000/api/parkingLots/ HTTP/1.1
content-type: application/json
//x-token: 

###GETBYID
GET http://localhost:8000/api/parkingLots/61bbf036c03b82d61cdc525e HTTP/1.1
content-type: application/json
//x-token: 

### UPDATE
PUT http://localhost:8000/api/parkingLots/61bbf039c03b82d61cdc5261 HTTP/1.1
content-type: application/json

{
    "userName": "admin",
    "calle": "avenida xyz",
    "numero": 987
}


### DELETE
DELETE http://localhost:8000/api/parkingLots/61bbf036c03b82d61cdc525e HTTP/1.1
content-type: application/json
//x-token: 